/// <reference path = "mock-data.d.ts" />

export const items = [
  {
    property_id: 'abc',
    name: 'Share Phòng Bao DNGS Ở Milpitas 95035',
    state: 'California',
    city: 'Milpitas',
    area: 'Milpitas 95035',
    code: 95035,
    description:
      '<p dir="ltr">I am renting out a private bedroom in my new house.</p><p dir="ltr">I’m an Eletrical Engineer in mid 20s working at a tech company. I’m looking for a clean and friendly male professional. The room is available on 6/15.</p><p dir="ltr">If this post is still up, the room is still available. To save time, please introduce yourself and your moving date when you message me. Thank you.</p><p dir="ltr">*The bedroom is not furnished</p><p dir="ltr">Contact me at 6152408318 (Peter Pham)</p>',
    property_type: 'Phòng Nhỏ',
    prices: [800],
    property_status: 'room_for_rent',
    property_size: null,
    images: [
      'https://thuenha.us/wp-content/uploads/2021/06/Screenshot_20210601-082942_Zillow-758x564.jpg',
      'https://thuenha.us/wp-content/uploads/2021/06/Screenshot_20210601-082734_Zillow.jpg',
      'https://thuenha.us/wp-content/uploads/2021/06/Screenshot_20210601-083007_Zillow.jpg',
    ],
    features: ['Air conditioning', 'Lawn', 'Washer', 'Wifi'],
    bathroom: null,
    bedroom: null,
    created_at: '',
    updated_at: '',
  },
  {
    property_id: 'abc2',
    name: 'Private Bedroom And Shared Bathroom For Rent (Free Utilities)',
    state: 'California',
    city: 'San Jose',
    area: 'Capitol',
    code: 95121,
    description:
      '<p>Cozy Room for rent in a Clean, Quiet Home in Milpitas for $600/month</p><p>Giá thuê: $600 (+1 month deposit)<br>Move in date: bắt đầu từ tháng 6, ngày 15</p><p>Liên lạc<br>chị Ngọc (510)760-1357<br>anh Andrew: (408)571-9883</p><p>#thuephong #sharephong #roomforrent</p>',
    property_type: 'Phòng Nhỏ',
    prices: [600],
    property_status: 'room_for_rent',
    property_size: null,
    images: [
      'https://thuenha.us/wp-content/uploads/2021/06/8C13168B-DA16-447D-8429-FB03FA0371E4.jpeg',
      'https://thuenha.us/wp-content/uploads/2021/06/1C5106FA-4582-40E4-A972-D0B3BF718BEE.jpeg',
      'https://thuenha.us/wp-content/uploads/2021/06/F8D9F844-224D-4496-BAEE-3DF839DEE12F.jpeg',
      'https://thuenha.us/wp-content/uploads/2021/06/ECE700C0-3083-4F24-B68E-045D4876B35A.jpeg',
    ],
    features: ['Microwave', 'Share bathroom', 'Refrigerator', 'Wifi'],
    bathroom: 1,
    bedroom: 1,
    created_at: '',
    updated_at: '',
  },
  {
    property_id: 'abc3',
    name:
      'Share 3 Phòng Có Wifi Giặt Sấy Kitchen Sân Vườn Parking Downtown San Jose 95122',
    state: 'California',
    city: 'San Jose',
    area: 'San Jose',
    code: 95122,
    description:
      '<p>Có nhà single house o downtown San jose 95122 cho share phòng, có wifi mạnh, giặt sấy, kitchen, sân vườn , parking.</p><p>Giá 1 tháng là:<br>Phòng nhỏ: $600<br>Phòng vừa : $700<br>Phòng lớn: $800<br>Cộng thêm $100 nếu thêm 1 người nữa<br>Liên hệ: 4159679473<br>Hãy cho tôi biết nếu bạn đọc tin này từ ThueNha.us nhé</p>',
    property_type: 'Phòng Nhỏ',
    prices: [600, 700, 800],
    property_status: 'room_for_rent',
    property_size: null,
    images: [
      'https://thuenha.us/wp-content/uploads/2021/06/F1884D33-7B4F-4542-B37A-43953923F160-758x564.jpeg',
    ],
    features: ['On-street parking', 'Parking Riêng'],
    bathroom: 1,
    bedroom: 3,
    created_at: '',
    updated_at: '',
  },
  {
    property_id: 'abc4',
    name:
      'Share Phòng Nhỏ 120sqft Share Bathroom Gần Chợ Ocean Khu Milpias 95035',
    state: 'Californial',
    city: 'Milpias',
    area: 'Gần chợ Ocean',
    code: 95035,
    description:
      '<p>Share phòng khu vực Milpias 95035.<br>Nếu mọi người có nhu cầu xin liên hệ – Vân (408) 646-0426</p>',
    property_type: 'Phòng Nhỏ',
    prices: [600],
    property_status: 'room_for_rent',
    property_size: null,
    images: [
      'https://thuenha.us/wp-content/uploads/2021/06/DB925C97-8698-481E-8310-32914D29E244.jpeg',
    ],
    features: ['Share Bathroom', 'Wifi'],
    bathroom: 1,
    bedroom: 1,
    created_at: '',
    updated_at: '',
  },
  {
    property_id: 'abc5',
    name: 'Share Phòng Bao DNGS Khu Tully Road Và Ruby Ave 95148',
    state: 'California',
    city: 'San Jose',
    area: 'Khu Tully Road va Ruby ave',
    code: 95148,
    description:
      '<p>Nhà dư 1 phòng cho thuê giá 650/1 tháng và deposit 1 tháng</p><p>Khu Tully road và Ruby ave, zip code 95148, bao điện nước, giặt sấy, Wifi, không nấu ăn, dọn vào bất cứ lúc nào</p><p>Ưu tiên nữ độc thân đi làm hay đi học</p><p>Vui lòng liên hệ số phone (408)3342632 gặp My</p><p>Có thể text hoặc gọi bất cứ lúc nào</p>',
    property_type: 'Phòng Nhỏ',
    prices: [650],
    property_status: 'room_for_rent',
    property_size: null,
    images: [
      'https://thuenha.us/wp-content/uploads/2021/06/889B7FE3-94E2-4BFD-85EA-0D8F85E3E294.jpeg',
      'https://thuenha.us/wp-content/uploads/2021/06/2DC4FE9D-717D-4B1C-A87E-A333A56F49D7.jpeg',
    ],
    features: ['Share Bathroom', 'Wifi'],
    bathroom: 1,
    bedroom: 1,
    created_at: '',
    updated_at: '',
  },
  {
    property_id: 'abc6',
    name: 'Share 3 Phòng Ngủ 1 Phòng Tắm 2 Parkings Khu Tully Quimby',
    state: 'California',
    city: 'San Jose',
    area: 'Khu Tully Road va Ruby ave',
    code: 95148,
    description:
      '<p>Nhà cho Share 3 pn lớn 1pt, 2 parkings, lối đi chung, 2 vc chủ nhà ở trên lầu, dọn vô đầu tháng 8.<br>Tully/Quimby, gần chợ Lion.<br>Xin liên lạc 408-832-5183<br></p>',
    property_type: 'Phòng Nhỏ',
    prices: [650],
    property_status: 'room_for_rent',
    property_size: null,
    images: [
      'https://thuenha.us/wp-content/uploads/2021/06/F88A1F07-37E5-44F5-A11F-6267281A8650.jpeg',
      'https://thuenha.us/wp-content/uploads/2021/06/9341E1F2-3BB9-4ADD-947E-B67E722F8537.jpeg',
    ],
    features: ['Bathroom Riêng', 'Parking Riêng'],
    bathroom: 1,
    bedroom: 3,
    created_at: '',
    updated_at: '',
  },
];
